# Build stage
FROM gradle:8.5-jdk21 AS build
WORKDIR /app
COPY . .
RUN gradle bootJar --no-daemon

# Run stage
FROM eclipse-temurin:21-jre
WORKDIR /app
COPY --from=build /app/newrelic/newrelic-agent.jar /app/newrelic-agent.jar
COPY --from=build /app/build/libs/*.jar app.jar
EXPOSE 8080
ENV JAVA_TOOL_OPTIONS="-javaagent:/app/newrelic-agent.jar"
ENTRYPOINT ["java", "-jar", "app.jar"]
