#!/bin/sh
echo "Executing pre-push hook..."
echo "Running build..."

# Move to repo root
cd "$(git rev-parse --show-toplevel)" || exit 1

# Run Gradle build
./gradlew build
if [ $? -ne 0 ]; then
  echo "Build failed, fix issues before committing this"
  exit 1
fi

echo "Build succeeded."
